// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxrSk2jIvWvk7EoOuafqPkr6EWXowBSTo',
    appId: '1:989310805609:web:e96bcb32ed178d7d3224f8',
    messagingSenderId: '989310805609',
    projectId: 'irfanach-36e20',
    authDomain: 'irfanach-36e20.firebaseapp.com',
    storageBucket: 'irfanach-36e20.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkJ6e7yWTBiiRwHxgUXNEjpnMzYKsi4UQ',
    appId: '1:989310805609:android:869abe69cc45f61d3224f8',
    messagingSenderId: '989310805609',
    projectId: 'irfanach-36e20',
    storageBucket: 'irfanach-36e20.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVKcgb1_NS1Xfc3cDNjIRrFfpwq2l09do',
    appId: '1:989310805609:ios:f53e9c89ee656d8d3224f8',
    messagingSenderId: '989310805609',
    projectId: 'irfanach-36e20',
    storageBucket: 'irfanach-36e20.appspot.com',
    iosBundleId: 'com.example.irfanach',
  );
}
